name: Check VERSIONLOG.MD has been updated
on: [pull_request]

jobs:
  check-versionlog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Check for VERSIONLOG.MD changes
        id: versionlog_check
        run: |
          PR_BASE_SHA=$(git merge-base HEAD ${{ github.event.pull_request.base.sha }})
          FILE_CHANGED=$(git diff --name-only $PR_BASE_SHA HEAD | grep 'VERSIONLOG.MD' || true)
          if [ -n "$FILE_CHANGED" ]; then
            echo "VERSIONLOG.MD has been changed."
          else
            echo "VERSIONLOG.MD has NOT been changed."
            exit 1 # Fail the workflow if no changes in VERSIONLOG.MD
          fi
